package sol;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.*;

import com.vaadin.annotations.AutoGenerated;

@Entity
@Table(name = "HIGHSCHOOL")
public class HighSchool {
	// Atributs

	@Id
	@Column
	@AutoGenerated
	private int id = 0;
	
	@OneToMany(cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
	private List<Teacher> lt = null;

	@OneToMany(cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
	private List<Student> ls = null;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	private List<Clas> lc = null;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	private List<Workshop> workshops = null;

	@Column(length = 50)
	private String name = null;
	
	@Column(length = 50)
	private String code = null;

	

	// constructor
	public HighSchool() {
		super();
	}

	public HighSchool(String name, String code) {
		this(name);
		setCode(code);
	}

	public HighSchool(String name) {
		super();
		setName(name);
	}

	public String getName() {
		return name;
	}

	private void setName(String name) {	
		name = name.trim().toUpperCase();
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	private void setCode(String code) {
		code = code.trim().toUpperCase();
		this.code = code;
	}

	public int getId() {
		return id;
	}

	private void setId(int id) {
		this.id = id;
	}

	public void addLT(Teacher t) {
		getLt().add(t);
	}

	public void addLS(Student s) {
		getLs().add(s);
	}

	public void addLC(Clas c) {
		getLc().add(c);
	}

	public List<Teacher> getLt() {
		if (lt == null)
			lt = new ArrayList<Teacher>();
		return lt;
	}

	public List<Student> getLs() {
		if (ls == null)
			ls = new ArrayList<Student>();
		return ls;
	}

	public List<Clas> getLc() {
		if (lc == null)
			lc = new ArrayList<Clas>();
		return lc;
	}

	public List<Workshop> getWorkshops() {
		if (workshops == null)
			workshops = new ArrayList<Workshop>();
		return workshops;
	}

	public void addWorkshops(Workshop workshop) {
		getWorkshops().add(workshop);
	}

}