ALTER TABLE XPRM DROP CONSTRAINT FK_XPRM_USER_ID
ALTER TABLE XUSR_XPRM DROP CONSTRAINT FK_XUSR_XPRM_permissions_XPXPID
ALTER TABLE XUSR_XPRM DROP CONSTRAINT FK_XUSR_XPRM_User_XUXUUSR
ALTER TABLE XUSR_XROL DROP CONSTRAINT FK_XUSR_XROL_users_XUXUUSR
ALTER TABLE XUSR_XROL DROP CONSTRAINT FK_XUSR_XROL_roles_XRXRID
DROP TABLE MAQUINA CASCADE
DROP TABLE XUSR CASCADE
DROP TABLE XROL CASCADE
DROP TABLE XPRM CASCADE
DROP TABLE XUSR_XPRM CASCADE
DROP TABLE XUSR_XROL CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
